name: Update Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'library/*.py'
      - '.github/workflows/docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container: osgeo/gdal:ubuntu-small-3.2.1
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        apt update
        apt install -y python3-pip python3-distutils
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

    - name: Poetry Install
      run: |
        . $HOME/.poetry/env
        poetry config virtualenvs.create false --local
        poetry install
        poetry run pdoc -o docs --html library

    - name: Commit output
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "ðŸŽ‰ Update Documentation"
        add: 'docs/'
