name: Update Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'library/*.py'
      - '.github/workflows/docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container: osgeo/gdal:ubuntu-small-3.2.1
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes

    steps:
    - uses: actions/checkout@v2

    - name: Set up GDAL and poetry
      run: |
        apt update
        apt install -y git python3-pip

    - name: Install Python dependencies, create docs
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install .
        python3.8 -m pip install pdoc
        python3.8 -m pdoc -o docs --html --force library

    - name: Commit files
      continue-on-error: true
      id: commit
      run: |
        ls -l docs/
        git status

        DATE=$(date)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "ðŸŽ‰ Update Docs $DATE" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
