name: Update Documentation

on:
  push:
    branches: 
      - main
    paths:
      - '*.py'
      - '.github/workflows/docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-20.04	
    container: debian:stable
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up GDAL and poetry
      run: |
        apt update
        apt install -y gdal-bin libgdal-dev python3-gdal
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
        
    - name: Create Docs using pdoc
      run: |
        source $HOME/.poetry/env
        poetry install
        poetry run pdoc -o docs --html library

    - name: Commit output
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "ðŸŽ‰ Update Documentation"
        add: 'docs/'
