name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: debian:stable
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up GDAL and poetry
      run: |
        apt update
        apt install -y gdal-bin libgdal-dev python3-gdal curl
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

    - name: Run pytests
      run: |
        source $HOME/.poetry/env
        poetry install
        poetry run pytest tests/test_utils.py -s
        poetry run pytest tests/test_config.py -s
        poetry run pytest tests/test_ingest.py -s
        poetry run pytest tests/test_s3.py -s
        poetry run pytest tests/test_archive.py -s
