name: Pytest

on:
  push:
    paths-ignore:
      - "*.html"
      - "*.md"

jobs:
  test:
    runs-on: ubuntu-20.04
    container: osgeo/gdal:ubuntu-small-3.2.1
    defaults:
      run:
        shell: bash
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        apt update
        apt install -y python3-pip python3-distutils
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

    - name: Poetry Install
      env:
        PATH: "$PATH:$HOME/.poetry/bin"
      run: |
        source $HOME/.poetry/env
        poetry config virtualenvs.create false --local

    - name: Pytests
      run: |
        source $HOME/.poetry/env
        poetry run pytest -s
